# ### Save or update calorie information
# POST http://localhost:8000/calinfo
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZpZGh5YUBnbWFpbC5jb20iLCJpYXQiOjE3MTc0Nzk0NDd9.IfbtTWfwaNr9KspcT8sSADUUEkLIF1JFL4RNaXt-wow

# {
#   "userId": "665760f15b0e2696acb42a54",
#   "date": "2024-06-04",
#   "totalCalories": 2100,
#   "caloriesConsumed": 1500,
#   "caloriesToGo": 500
# }
## Get calorie information for a specific user on the current date
GET http://localhost:8000/calinfo/665760f15b0e2696acb42a54
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZpZGh5YUBnbWFpbC5jb20iLCJpYXQiOjE3MTc0Nzk0NDd9.IfbtTWfwaNr9KspcT8sSADUUEkLIF1JFL4RNaXt-wow
Accept: application/json
